services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: fakegister
      MARIADB_USER: fakegister
      MARIADB_DATABASE: fakegister
    volumes:
      - db:/var/lib/mysql

volumes:
  db: